version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "src/Moneybird.Net"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "03:00"
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
        - '*'
  - package-ecosystem: "nuget"
    directory: "tests/Moneybird.Net.Tests"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "03:00"
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
        - '*'
    ignore:
      - dependency-name: "FluentAssertions"
        update-types: ["version-update:semver-major"]
  
